version: '3.8' 

services:
  db:
    image: postgres
    container_name: qraft-db
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qraft-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:  