[workspace]
resolver = '2'
members = ["models"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.18.1", features = ["serde", "v4"] }
chrono = { version = "*", features = ["serde"] }
